from selenium.webdriver.common.by import By


class Locators:
    ACCEPT_COOKIES = (By.XPATH, "//button[@data-btn = 'yes']")
    REFUSE_COOKIES = (By.XPATH, "//button[@data-btn = 'no']")
    COOKIES_BLOCK = (By.XPATH, "//div[@id = 'Cks']")
    SKIP_BUTTON = (By.XPATH, "//button[@data-btn = 'skip']")
    LEARN_MORE_BUTTON = (By.XPATH, "//a[@rel = 'noopener']")
    SOUND_BUTTON = (By.XPATH, "//button[@class = 'o-B o-BCircle js-show']")
    INTRO_IS_OVER = (By.XPATH, "//div[@class = 'c-Intro u-fixed u-post-tl u-fit u-hidden']")
    DROPDOWN_MENU_OPEN = (By.XPATH, "//button[@class = 'o-B o-BBurger']")
    DROPDOWN_MENU_IS_OPEN = (By.XPATH, "//div[@style = 'visibility: visible;']")
    DROPDOWN_MENU_CLOSE = (By.XPATH, "//button[@class = 'o-B o-BClose']")
    DROPDOWN_ITEMS = (By.XPATH, "//li[@class = 'js-it']")
    DROPDOWN_MAIN_ITEMS = (By.XPATH, "//a[contains(@class, 'o-B o-BS o-BS-invert js-btn')]")
    DROPDOWN_SUB_ITEMS = (By.XPATH, "//a[contains(@class, 'o-B o-BS o-BSubProduct o-BS-invert js-btn')]")
    SLIDER_ITEMS = (By.XPATH, "//span[@class = 'o-P1 -L js-l']")
    SLIDER_TOMATOES = (By.XPATH, "//button[@data-id = 'tomatoes']")
    SLIDER_CITRUS = (By.XPATH, "//button[@data-id = 'citrus']")
    SLIDER_GRAPES = (By.XPATH, "//button[@data-id = 'grapes']")
    SLIDER_AVOCADOS = (By.XPATH, "//button[@data-id = 'avocados']")
    SLIDER_FLOWERS = (By.XPATH, "//button[@data-id = 'flowers']")
    LEGALS_BUTTON = (By.XPATH, "//a[@data-btn = 'legals']")
    RU_BUTTON = (By.XPATH, "//a[@data-lang = 'ru']")
    REPLAY_VIDEO = (By.XPATH, "//a[@data-btn = 'replay']")
    VIDEO_IS_PLAYING = (By.XPATH, "//div[@class= 'c-Player is-playing']")
    CLOSE_REPLAY = (By.XPATH, "//a[@class= 'o-B o-BClose']")
    DISCOVER_BUTTON = (By.XPATH, "//a[@data-btn = 'discover']")
    PAGE_H3 = (By.XPATH, "//h3")
    PAGE_H2 = (By.XPATH, "//h2")
    PAGE_PRODUCT_BLOCK = (By.XPATH, "//a[@data-id = 'card']")
    ANY_QUESTIONS_BLOCK = (By.XPATH, "//div[@class = 'l-S l-S--l ']")
    SECOND_BLOCK = (By.XPATH, "//div[@class = 'l-IC']")
    CONTACT_US_BUTTON = (By.XPATH, "//a[@data-btn = 'contact']")
    LOGO = (By.XPATH, "//a[@class = 'o-B']")
